use std::{
    env, fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};

const BUNDLED_CONFIG: &str = include_str!("bundled.gitconfig");

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub enum ConfigSource {
    /// Use the small configuration compiled into the executable.
    #[default]
    Bundled,
    /// Use the local configuration of the project containing the current directory.
    Project,
    /// Use XDG and home-directory Git configuration files, in Git's precedence order.
    User,
    /// Use the platform's system-wide Git configuration file, when present.
    System,
    /// Use exactly one explicitly named Git configuration file.
    File(PathBuf),
}

#[derive(Debug)]
pub(crate) struct PreparedConfig {
    path: PathBuf,
}

impl PreparedConfig {
    pub(crate) fn path(&self) -> &Path {
        &self.path
    }
}

pub(crate) fn prepare(
    source: &ConfigSource,
    current_dir: &Path,
    work_dir: &Path,
) -> Result<PreparedConfig> {
    let path = work_dir.join("gitconfig");
    let contents = match source {
        ConfigSource::Bundled => BUNDLED_CONFIG.to_owned(),
        ConfigSource::File(selected) => {
            let selected = existing_file(absolute(selected, current_dir)?, "Git configuration")?;
            include_config(&[selected])?
        }
        ConfigSource::Project => {
            let files = project_config_files(current_dir)?;
            include_config(&files)?
        }
        ConfigSource::User => include_config(&user_config_files())?,
        ConfigSource::System => include_config(&system_config_files())?,
    };
    fs::write(&path, contents)
        .with_context(|| format!("Failed to prepare Git configuration at {}", path.display()))?;

    #[cfg(feature = "backend-git2")]
    git2::Config::open(&path)
        .with_context(|| format!("Invalid Git configuration selected via {}", path.display()))?;

    Ok(PreparedConfig { path })
}

fn include_config(paths: &[PathBuf]) -> Result<String> {
    let mut contents = String::from(
        "# Generated by get-git. Only the explicitly selected sources are included.\n",
    );
    if paths.is_empty() {
        return Ok(contents);
    }
    contents.push_str("[include]\n");
    for path in paths {
        contents.push_str("\tpath = \"");
        contents.push_str(&escape_path(path)?);
        contents.push_str("\"\n");
    }
    Ok(contents)
}

fn escape_path(path: &Path) -> Result<String> {
    let value = path.to_str().with_context(|| {
        format!(
            "Git configuration path is not valid UTF-8: {}",
            path.display()
        )
    })?;
    #[cfg(windows)]
    let value = value.replace('\\', "/");
    #[cfg(not(windows))]
    let value = value.to_owned();

    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\t' => escaped.push_str("\\t"),
            '\u{8}' => escaped.push_str("\\b"),
            other => escaped.push(other),
        }
    }
    Ok(escaped)
}

fn absolute(path: &Path, current_dir: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(current_dir.join(path))
    }
}

fn existing_file(path: PathBuf, label: &str) -> Result<PathBuf> {
    if !path.is_file() {
        bail!("{label} is not a readable file: {}", path.display());
    }
    Ok(path)
}

fn project_config_files(current_dir: &Path) -> Result<Vec<PathBuf>> {
    for ancestor in current_dir.ancestors() {
        let dot_git = ancestor.join(".git");
        if dot_git.is_dir() {
            let config = dot_git.join("config");
            if config.is_file() {
                return Ok(with_optional_worktree_config(config, &dot_git));
            }
        } else if dot_git.is_file() {
            let git_dir = resolve_git_dir_file(&dot_git)?;
            let common_dir = resolve_common_dir(&git_dir)?;
            let config = common_dir.join("config");
            if config.is_file() {
                return Ok(with_optional_worktree_config(config, &git_dir));
            }
        }

        // Also support running from the root of a bare repository.
        if ancestor.join("HEAD").is_file()
            && ancestor.join("objects").is_dir()
            && ancestor.join("config").is_file()
        {
            return Ok(vec![ancestor.join("config")]);
        }
    }
    bail!("--project-config requires the current directory to be inside a Git repository")
}

fn with_optional_worktree_config(config: PathBuf, git_dir: &Path) -> Vec<PathBuf> {
    let mut files = vec![config];
    let worktree = git_dir.join("config.worktree");
    if worktree.is_file() {
        files.push(worktree);
    }
    files
}

fn resolve_git_dir_file(dot_git: &Path) -> Result<PathBuf> {
    let contents = fs::read_to_string(dot_git)
        .with_context(|| format!("Failed to read linked-worktree file {}", dot_git.display()))?;
    let value = contents
        .trim()
        .strip_prefix("gitdir:")
        .map(str::trim)
        .context("The project's .git file does not contain a gitdir pointer")?;
    let path = PathBuf::from(value);
    Ok(if path.is_absolute() {
        path
    } else {
        dot_git.parent().expect(".git file has a parent").join(path)
    })
}

fn resolve_common_dir(git_dir: &Path) -> Result<PathBuf> {
    let path = git_dir.join("commondir");
    if !path.is_file() {
        return Ok(git_dir.to_path_buf());
    }
    let value =
        fs::read_to_string(&path).with_context(|| format!("Failed to read {}", path.display()))?;
    let common = PathBuf::from(value.trim());
    Ok(if common.is_absolute() {
        common
    } else {
        git_dir.join(common)
    })
}

fn user_config_files() -> Vec<PathBuf> {
    let Some(home) = home_dir() else {
        return Vec::new();
    };
    let xdg = env::var_os("XDG_CONFIG_HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join(".config"));
    [xdg.join("git/config"), home.join(".gitconfig")]
        .into_iter()
        .filter(|path| path.is_file())
        .collect()
}

fn home_dir() -> Option<PathBuf> {
    env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            env::var_os("USERPROFILE")
                .filter(|value| !value.is_empty())
                .map(PathBuf::from)
        })
        .or_else(|| {
            let drive = env::var_os("HOMEDRIVE")?;
            let path = env::var_os("HOMEPATH")?;
            Some(PathBuf::from(drive).join(path))
        })
}

fn system_config_files() -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    #[cfg(windows)]
    {
        for root in [
            env::var_os("PROGRAMFILES"),
            env::var_os("ProgramFiles(x86)"),
            env::var_os("LOCALAPPDATA")
                .map(|path| PathBuf::from(path).join("Programs").into_os_string()),
        ]
        .into_iter()
        .flatten()
        {
            candidates.push(PathBuf::from(root).join("Git/etc/gitconfig"));
        }
    }
    #[cfg(not(windows))]
    {
        candidates.push(PathBuf::from("/etc/gitconfig"));
        candidates.push(PathBuf::from("/usr/local/etc/gitconfig"));
    }
    candidates
        .into_iter()
        .filter(|path| path.is_file())
        .take(1)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_config_is_valid_and_portable() {
        let temp = tempfile::tempdir().unwrap();
        let prepared = prepare(&ConfigSource::Bundled, temp.path(), temp.path()).unwrap();
        let text = fs::read_to_string(prepared.path()).unwrap();
        assert!(text.contains("sslVerify = true"));
        assert!(!text.contains("credential.helper"));
        assert!(!text.contains("proxy"));
    }

    #[cfg(feature = "backend-git2")]
    #[test]
    fn explicit_config_is_the_only_included_source() {
        let temp = tempfile::tempdir().unwrap();
        let selected = temp.path().join("selected.gitconfig");
        fs::write(&selected, "[http]\n\tuserAgent = test-agent\n").unwrap();
        let work = temp.path().join("work");
        fs::create_dir(&work).unwrap();
        let prepared = prepare(&ConfigSource::File(selected), temp.path(), &work).unwrap();
        let config = git2::Config::open(prepared.path()).unwrap();
        assert_eq!(config.get_string("http.userAgent").unwrap(), "test-agent");
        assert!(config.get_string("user.name").is_err());
    }

    #[test]
    fn discovers_project_config_without_invoking_git() {
        let temp = tempfile::tempdir().unwrap();
        let nested = temp.path().join("project/src/nested");
        fs::create_dir_all(&nested).unwrap();
        let dot_git = temp.path().join("project/.git");
        fs::create_dir(&dot_git).unwrap();
        fs::write(dot_git.join("config"), "[http]\n\tsslVerify = true\n").unwrap();
        let files = project_config_files(&nested).unwrap();
        assert_eq!(files, vec![dot_git.join("config")]);
    }
}
